name:                megastore
version:             0.1.0.0
github:              "MilesLitteral/megastore"
license:             BSD3
author:              "Miles J. Litteral"
maintainer:          "mandaloe2@gmail.com"
copyright:           "2023 Miles J. Litteral"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Bulk image or strict bytestring storage
category:            Data Structures, Data, Image
description:         Please see the README on GitHub at <https://github.com/MilesLitteral/megastore/tree/release#readme>

dependencies:
- base        >= 4.7      && <  5
- ghc         >= 9.4.2    && <= 9.4.4
- bytestring  >  0.10.0.0 && <= 0.11.4.0
- lens        >  5        && <= 5.2
- adjunctions >  4.2      && <= 4.4.2
- hashable    >  1.2.3.0  && <= 1.4.2.0
- binary      >  0.8.0.0  && <= 0.8.9.1
- JuicyPixels >  3.3.4    && <= 3.3.8
- vector      >  0.12.1.2 && <= 0.13.0.0
- mtl         >  2.2      && <= 2.2.2 
- zlib        >  0.6.0.0  && <= 0.6.3.0
- directory   >  1.3.0.0  && <= 1.3.8.0 
- random      >= 1.1      && <= 1.2.1.1
- text        >= 2.0      && <= 2.0.2
- text-show   >= 3.9.5    && <= 3.10
- containers  >= 0.6.4.1  && <= 0.6.7

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  megastore:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - megastore


